server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: 192.168.10.137:8848
    sentinel:
      transport:
        #sentinel dashboard地址
        dashboard: 192.168.10.137:8858
        #默认8719端口，假如被占用会自动从8719开始依次扫描，直到找到未被占用的端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
